# Copyright Contributors to the Open Cluster Management project

## Append samples you want in your CSV to this file as resources ##
resources:
# - discovery_v1_discoveredcluster.yaml
- discovery_v1_discoveryconfig.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
